services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  collector:
    build:
      context: .
      dockerfile: ./collector/Dockerfile
    command: ["node", "collector.js"]
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    command: ["node", "worker.js"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    command: ["node", "producer.js"]
    depends_on:
      - collector
    environment:
      - COLLECTOR_ADDRESS=collector:50051
